name: Deploy Flask App to Google Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure gcloud project
        run: |
          echo "Setting project to ${{ secrets.GCP_PROJECT_ID }}"
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"
          gcloud config list

      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-devops-demo .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-devops-demo \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-devops-demo \
            --region=us-central1 \
            --platform=managed \
            --allow-unauthenticated
