name: Deploy Flask App to Google Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Google Cloud CLI
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # 3️⃣ Build and push the Docker image to Google Container Registry
      - name: Build & push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-devops-demo .

      # 4️⃣ Deploy the image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-devops-demo \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flask-devops-demo \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
